const {Schema, model} = require('mongoose')


const MPSchema = new Schema({
    REG_CASO_NO: String,
    REG_ANIO: String,
    MES_REG: String,
    REG_DIA: String,
    REG_MUNI: String,
    QUIEN_REPORTA: String,
    VIC_NOM: String,
    VIC_SEXO: String,
    VIC_EDAD: String,
    VIC_ANIO_NAC: String,
    VIC_MES_NAC: String,
    VIC_DIA_NAC: String,
    VIC_HIJ_TOT: String,
    VIC_HIJ_SEX: String,
    VIC_HIJ_EDAD: String,
    VIC_ALFAB: String,
    VIC_ESCOLARIDAD: String,
    VIC_EST_CONY: String,
    VIC_MUNI_RES: String,
    VIC_PUEB_PER: String,
    VIC_NACIONAL: String,
    VIC_TRABAJA: String,
    VIC_OCUP: String,
    VIC_DEDICA: String,
    VIC_DISC: String,
    VIC_TIPO_DISC: String,
    VIC_REL_AGR: String,
    ESP_OTR_REL: String,
    OTRAS_VICTIMAS: String,
    OTRAS_VIC_SEX: String,
    OTRAS_VIC_EDAD: String,
    OTRAS_VIC_REL: String,
    HEC_DIA: String,
    HEC_MES: String,
    HEC_ANO: String,
    HEC_DEPTOMCPIO: String,
    HEC_AREA: String,
    HEC_TIPAGRE: String,
    HEC_RECUR_CASO: String,
    INST_RECUR_CASO: String,
    AGR_SEXO: String,
    AGR_EDAD: String,
    AGR_ALFAB: String,
    AGR_ESCOLARIDAD: String,
    AGR_EST_CONY: String,
    AGR_PUEB_PER: String,
    AGR_NACIONAL: String,
    AGR_TRABAJA: String,
    AGR_OCUP: String,
    AGR_DEDICA: String,
    OTROS_AGR_TOT: String,
    OTROS_AGR_SEX: String,
    OTROS_AGR_EDAD: String,
    OTROS_AGR_REL: String,
    DIL_GES: String,
    REM_CASO: String,
    REG_INST_HECH: String
},{
    timestamps:true
})

module.exports = model('MP', MPSchema)
